# Generated by Django 4.1.4 on 2022-12-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='id',
        ),
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
