# Generated by Django 4.1.4 on 2022-12-16 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_remove_usertype_id_alter_usertype_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(3)])),
                ('committed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(12)])),
            ],
        ),
    ]
